# run_simics.ps1 - echOS Simics tek tusla boot
# Kullanim:
#   .\run_simics.ps1                         # Debug build + GUI
#   .\run_simics.ps1 -Release                # Release build + GUI
#   .\run_simics.ps1 -NoBuild                # Build atlayip mevcut EFI ile
#   .\run_simics.ps1 -BatchMode              # Ekransiz batch mod
#   .\run_simics.ps1 -CheckOnly              # Simics/VMP/EFI ortam kontrolu
#   .\run_simics.ps1 -BatchMode -RequireVmp  # VMP yoksa kapidan gecirme
#   .\run_simics.ps1 -NoBuild -SkipDiskUpdate # VHDX mount etmeden mevcut diskle ac

param(
    [switch]$NoBuild,
    [switch]$Release,
    [switch]$BatchMode,
    [switch]$CheckOnly,
    [switch]$RequireVmp,
    [switch]$SkipDiskUpdate,
    [ValidateRange(1, 8192)][int]$Cores = 2,
    [ValidateRange(0, 1000)][int]$SerialTailLines = 80,
    [int]$TimeoutSec = 3600 # 1 hour default (removed hard timeout from scripts)
)

$ErrorActionPreference = 'Stop'
$ProjectRoot   = $PSScriptRoot
$SimicsProject = Join-Path $ProjectRoot "Simics\echos-simics"
$VhdxPath      = Join-Path $SimicsProject "targets\echos\images\echos-uefi-fixed.vhdx"
$SimicsBat     = Join-Path $SimicsProject "simics.bat"
$SimicsGui     = "D:\Intel Simics Package Manager\simics-simics-gui-external-7.0.3\simics-gui.exe"
$GuiScript     = "targets/echos/gui-boot.simics"
$BatchScript   = "targets/echos/zero-tolerance-gate.simics"
$Log           = Join-Path $ProjectRoot "vhdx_update.log"
$DiskHelper    = Join-Path $ProjectRoot "run_simics_disk_helper.ps1"
$SimicsLogDir  = Join-Path $SimicsProject "targets\echos\logs"
$DisplayWidth  = 1920
$DisplayHeight = 1080

function Format-StatusBool {
    param([bool]$Value)
    if ($Value) { return "OK" }
    return "NO"
}

function Get-VmpDriverStatus {
    $driver = Get-CimInstance Win32_SystemDriver -Filter "Name='vmxmon'" -ErrorAction SilentlyContinue
    if ($null -eq $driver) {
        return [pscustomobject]@{
            Installed = $false
            Running   = $false
            State     = "missing"
            StartMode = "missing"
            Path      = ""
        }
    }

    return [pscustomobject]@{
        Installed = $true
        Running   = ($driver.State -eq "Running")
        State     = $driver.State
        StartMode = $driver.StartMode
        Path      = $driver.PathName
    }
}

function Test-RequiredPath {
    param(
        [Parameter(Mandatory)][string]$Label,
        [Parameter(Mandatory)][string]$Path
    )

    $exists = Test-Path $Path
    $color = if ($exists) { "Green" } else { "Red" }
    Write-Host ("  {0,-12}: {1}  {2}" -f $Label, (Format-StatusBool $exists), $Path) -ForegroundColor $color
    return $exists
}

function New-SimicsRunScript {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Mode,
        [Parameter(Mandatory)][string]$SerialCaptureSimicsPath,
        [Parameter(Mandatory)][int]$CoreCount,
        [Parameter(Mandatory)][int]$TimeoutSeconds,
        [Parameter(Mandatory)][int]$DisplayWidth,
        [Parameter(Mandatory)][int]$DisplayHeight
    )

    $modeLabel = if ($Mode -eq "batch") { "Zero-Tolerance Batch" } else { "GUI Boot" }
    $batchFooter = @()
    if ($Mode -eq "batch") {
        $batchFooter = @(
            'echo "[GATE] RUN_COMPLETE"',
            'board.mb.cpu0.core[0][0].pregs',
            'echo "[GATE] END"',
            'quit'
        )
    }

    $lines = @(
        "# Generated by run_simics.ps1; do not edit by hand.",
        "# Mode: $modeLabel",
        '$disk0_image = "targets/echos/images/echos-uefi-fixed.vhdx"',
        '$machine_name = "board"',
        '$show_con0 = TRUE',
        '$create_network = FALSE',
        "`$num_cores = $CoreCount",
        'run-script "%simics%/targets/qsp-x86/qsp-hdd-boot.simics"',
        '',
        "board.serconsole.con.capture-start `"$SerialCaptureSimicsPath`"",
        'board.serconsole.con.enable-cmd-line-output',
        '',
        'log-type -disable unimpl',
        'log-type -disable spec-viol',
        '',
        'echo "================================================"',
        "echo `"  echOS Simics $modeLabel`"",
        "echo `"  cores=$CoreCount timeout=${TimeoutSeconds}s`"",
        "echo `"  display=${DisplayWidth}x${DisplayHeight}`"",
        'echo "================================================"',
        "echo `"[GATE] START profile=simics-launcher mode=$Mode`"",
        'run'
    ) + $batchFooter

    $lines | Set-Content -Path $Path -Encoding ASCII
}

function Invoke-SimicsBatch {
    param(
        [Parameter(Mandatory)][string]$SimicsBatPath,
        [Parameter(Mandatory)][string]$ScriptPathForSimics,
        [Parameter(Mandatory)][string]$WorkingDirectory,
        [Parameter(Mandatory)][string]$StdoutPath,
        [Parameter(Mandatory)][string]$StderrPath,
        [Parameter(Mandatory)][int]$TimeoutSeconds
    )

    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName = $env:ComSpec
    $psi.Arguments = "/d /c `"`"$SimicsBatPath`" --batch-mode `"$ScriptPathForSimics`"`""
    $psi.WorkingDirectory = $WorkingDirectory
    $psi.UseShellExecute = $false
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError = $true
    $psi.CreateNoWindow = $true

    $proc = New-Object System.Diagnostics.Process
    $proc.StartInfo = $psi
    [void]$proc.Start()

    $stdoutTask = $proc.StandardOutput.ReadToEndAsync()
    $stderrTask = $proc.StandardError.ReadToEndAsync()
    $timeoutMs = [Math]::Max(1, $TimeoutSeconds) * 1000
    $completed = $proc.WaitForExit($timeoutMs)
    if (-not $completed) {
        try {
            & taskkill.exe /PID $proc.Id /T /F | Out-Null
        } catch {
            Write-Host "  [UYARI] Simics timeout sonrasi process-tree kill basarisiz: $($_.Exception.Message)" -ForegroundColor Yellow
            try {
                $proc.Kill()
            } catch {
                Write-Host "  [UYARI] Simics timeout sonrasi root process kill basarisiz: $($_.Exception.Message)" -ForegroundColor Yellow
            }
        }
        [void]$proc.WaitForExit(10000)
    }

    if ($stdoutTask.Wait(10000)) {
        $stdoutTask.Result | Set-Content -Path $StdoutPath -Encoding UTF8
    } else {
        "[run_simics] stdout read timed out after process-tree termination" | Set-Content -Path $StdoutPath -Encoding UTF8
    }
    if ($stderrTask.Wait(10000)) {
        $stderrTask.Result | Set-Content -Path $StderrPath -Encoding UTF8
    } else {
        "[run_simics] stderr read timed out after process-tree termination" | Set-Content -Path $StderrPath -Encoding UTF8
    }

    return [pscustomobject]@{
        TimedOut = (-not $completed)
        ExitCode = if ($completed) { $proc.ExitCode } else { 124 }
    }
}

function Get-SerialVerdict {
    param(
        [Parameter(Mandatory)][string]$SerialPath,
        [Parameter(Mandatory)][int]$TailLines
    )

    if (-not (Test-Path $SerialPath)) {
        return [pscustomobject]@{
            Exists = $false
            Bytes = 0
            PanicCount = 0
            FatalCount = 0
            BootControl = $false
            LoginVisible = $false
            UefiEntry = $false
            Tail = @()
        }
    }

    $content = Get-Content $SerialPath
    $text = $content -join "`n"
    return [pscustomobject]@{
        Exists = $true
        Bytes = (Get-Item $SerialPath).Length
        PanicCount = ([regex]::Matches($text, '\[PANIC\]|panic', 'IgnoreCase')).Count
        FatalCount = ([regex]::Matches($text, '\bFATAL\b|\bfatal\b')).Count
        BootControl = ($text -match 'BOOTCTRL success')
        LoginVisible = ($text -match 'login-visible')
        UefiEntry = ($text -match '\[UEFI\] EFI Entry Point Reached!')
        Tail = if ($TailLines -gt 0) { $content | Select-Object -Last $TailLines } else { @() }
    }
}

if (-not (Test-Path $SimicsLogDir)) {
    New-Item -ItemType Directory -Path $SimicsLogDir -Force | Out-Null
}

$Profile = if ($Release) { "release" } else { "debug" }
$EfiPath = Join-Path $ProjectRoot "target\x86_64-unknown-uefi\$Profile\ech_os.efi"
$RunStamp = Get-Date -Format "yyyyMMdd_HHmmss"
$SerialCaptureName = "serial_run_simics_$RunStamp.txt"
$SerialCapture = Join-Path $SimicsLogDir $SerialCaptureName
$SerialCaptureSimics = "targets/echos/logs/$SerialCaptureName"
$GeneratedScriptName = "run_simics_$RunStamp.simics"
$GeneratedScript = Join-Path $SimicsLogDir $GeneratedScriptName
$GeneratedScriptSimics = "targets/echos/logs/$GeneratedScriptName"
$StdoutLog = Join-Path $SimicsLogDir "run_simics_stdout_$RunStamp.log"
$StderrLog = Join-Path $SimicsLogDir "run_simics_stderr_$RunStamp.log"
$VmpStatus = Get-VmpDriverStatus

Write-Host ""
Write-Host "  =============================" -ForegroundColor Cyan
Write-Host "   echOS Simics Boot Launcher"   -ForegroundColor Cyan
Write-Host "  =============================" -ForegroundColor Cyan
Write-Host "  Profil : $Profile"
$modStr = if ($BatchMode) { "Batch (ekransiz)" } else { "GUI (pencereli)" }
Write-Host "  Mod    : $modStr"
Write-Host "  Core   : $Cores"
Write-Host "  Ekran  : ${DisplayWidth}x${DisplayHeight}"
Write-Host "  VMP    : installed=$(Format-StatusBool $VmpStatus.Installed) running=$(Format-StatusBool $VmpStatus.Running) state=$($VmpStatus.State) start=$($VmpStatus.StartMode)"
Write-Host ""

$pathsOk = $true
$pathsOk = (Test-RequiredPath "Project" $SimicsProject) -and $pathsOk
$pathsOk = (Test-RequiredPath "Simics" $SimicsBat) -and $pathsOk
$pathsOk = (Test-RequiredPath "VHDX" $VhdxPath) -and $pathsOk
$pathsOk = (Test-RequiredPath "Helper" $DiskHelper) -and $pathsOk
if (Test-Path $SimicsGui) {
    Write-Host ("  {0,-12}: {1}  {2}" -f "GUI", "OK", $SimicsGui) -ForegroundColor Green
} else {
    Write-Host ("  {0,-12}: {1}  {2}" -f "GUI", "NO", $SimicsGui) -ForegroundColor Yellow
}
if (Test-Path $EfiPath) {
    Write-Host ("  {0,-12}: {1}  {2}" -f "EFI", "OK", $EfiPath) -ForegroundColor Green
} elseif ($NoBuild -or $CheckOnly) {
    Write-Host ("  {0,-12}: {1}  {2}" -f "EFI", "NO", $EfiPath) -ForegroundColor Yellow
}

if ($RequireVmp -and -not $VmpStatus.Running) {
    Write-Host "[HATA] -RequireVmp istendi ama vmxmon driver Running degil." -ForegroundColor Red
    exit 2
}

if ($CheckOnly) {
    Write-Host ""
    Write-Host "[CHECK] Simics --version:" -ForegroundColor Yellow
    if (Test-Path $SimicsBat) {
        & $SimicsBat --version
    }
    if (-not $pathsOk) { exit 1 }
    if ($RequireVmp -and -not $VmpStatus.Running) { exit 2 }
    Write-Host "[CHECK] Ortam kontrolu tamam." -ForegroundColor Green
    exit 0
}

if (-not $pathsOk) {
    Write-Host "[HATA] Zorunlu Simics dosyalari eksik." -ForegroundColor Red
    exit 1
}

# --- 1. Build ---
if (-not $NoBuild) {
    Write-Host "[1/3] Derleniyor ($Profile)..." -ForegroundColor Yellow
    $buildArgs = @("build", "--target", "x86_64-unknown-uefi", "--features", "simics")
    if ($Release) { $buildArgs += "--release" }

    $prevPref = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    & cargo @buildArgs 2>&1 | ForEach-Object {
        $line = $_.ToString()
        if ($line -match 'error\[') { Write-Host $line -ForegroundColor Red }
        elseif ($line -match 'warning') { Write-Host $line -ForegroundColor Yellow }
        elseif ($line -match 'Compiling|Finished') { Write-Host "  $line" -ForegroundColor DarkGray }
    }
    $ErrorActionPreference = $prevPref
    if (-not (Test-Path $EfiPath)) {
        Write-Host "[HATA] Build basarisiz: $EfiPath bulunamadi" -ForegroundColor Red
        exit 1
    }
    $sz = (Get-Item $EfiPath).Length
    Write-Host "  EFI binary: $([math]::Round($sz/1KB)) KB" -ForegroundColor Green
} else {
    Write-Host "[1/3] Build atlandi (-NoBuild)" -ForegroundColor DarkGray
    if (-not (Test-Path $EfiPath)) {
        Write-Host "[HATA] $EfiPath bulunamadi. -NoBuild kaldirip tekrar calistir." -ForegroundColor Red
        exit 1
    }
}

# --- 2. VHDX Guncelle ---
if ($SkipDiskUpdate) {
    Write-Host "[2/3] VHDX guncelleme atlandi (-SkipDiskUpdate)" -ForegroundColor DarkGray
} else {
    Write-Host "[2/3] VHDX guncelleniyor..." -ForegroundColor Yellow

    $isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

    if ($isAdmin) {
        & $DiskHelper -VhdxPath $VhdxPath -EfiPath $EfiPath -LogPath $Log
    } else {
        Write-Host "  UAC penceresi cikacak - Evet e tikla" -ForegroundColor Magenta
        Start-Process powershell -Verb RunAs -ArgumentList "-ExecutionPolicy Bypass -File `"$DiskHelper`" -VhdxPath `"$VhdxPath`" -EfiPath `"$EfiPath`" -LogPath `"$Log`"" -Wait
    }

    if (Test-Path $Log) {
        $logContent = Get-Content $Log -Raw
        if ($logContent -match 'MATCH=True') {
            Write-Host "  VHDX guncellendi (SHA256 OK)" -ForegroundColor Green
        } elseif ($logContent -match 'SKIP') {
            Write-Host "  VHDX zaten guncel" -ForegroundColor Green
        } else {
            Write-Host "  [UYARI] Sonuc belirsiz:" -ForegroundColor Yellow
            Write-Host "  $logContent" -ForegroundColor DarkGray
        }
    }
}

# --- 3. Simics Baslat ---
Write-Host "[3/3] Simics baslatiliyor..." -ForegroundColor Yellow
New-SimicsRunScript -Path $GeneratedScript -Mode $(if ($BatchMode) { "batch" } else { "gui" }) -SerialCaptureSimicsPath $SerialCaptureSimics -CoreCount $Cores -TimeoutSeconds $TimeoutSec -DisplayWidth $DisplayWidth -DisplayHeight $DisplayHeight
Write-Host "  Script : $GeneratedScriptSimics" -ForegroundColor DarkCyan
Write-Host "  Serial : $SerialCapture" -ForegroundColor DarkCyan

Push-Location $SimicsProject
try {
    if ($BatchMode) {
        Write-Host "  Batch mod: $TimeoutSec sn simulasyon" -ForegroundColor DarkCyan
        $batchResult = Invoke-SimicsBatch -SimicsBatPath $SimicsBat -ScriptPathForSimics $GeneratedScriptSimics -WorkingDirectory $SimicsProject -StdoutPath $StdoutLog -StderrPath $StderrLog -TimeoutSeconds $TimeoutSec
        Write-Host "  stdout: $StdoutLog" -ForegroundColor DarkCyan
        Write-Host "  stderr: $StderrLog" -ForegroundColor DarkCyan
        if ($batchResult.TimedOut) {
            Write-Host "  [!] Simics timeout: $TimeoutSec sn sonunda durduruldu" -ForegroundColor Yellow
        } elseif ($batchResult.ExitCode -ne 0) {
            Write-Host "  [!] Simics exit code: $($batchResult.ExitCode)" -ForegroundColor Red
        } else {
            Write-Host "  Simics exit code: 0" -ForegroundColor Green
        }

        Write-Host ""
        $verdict = Get-SerialVerdict -SerialPath $SerialCapture -TailLines $SerialTailLines
        if ($verdict.Exists) {
            $hasFailure = ($verdict.PanicCount -gt 0) -or ($verdict.FatalCount -gt 0) -or $batchResult.TimedOut -or ($batchResult.ExitCode -ne 0)
            $col = if ($hasFailure) { "Red" } else { "Green" }
            Write-Host "  Serial: $($verdict.Bytes) byte" -ForegroundColor $col
            Write-Host "  Markers: UEFI=$(Format-StatusBool $verdict.UefiEntry) BOOTCTRL=$(Format-StatusBool $verdict.BootControl) LOGIN=$(Format-StatusBool $verdict.LoginVisible) PANIC=$($verdict.PanicCount) FATAL=$($verdict.FatalCount)" -ForegroundColor $col
            if ($hasFailure -and $verdict.Tail.Count -gt 0) {
                Write-Host "  --- serial tail ---" -ForegroundColor Yellow
                $verdict.Tail | ForEach-Object { Write-Host "  $_" -ForegroundColor DarkGray }
            } else {
                Write-Host "  Panic/FATAL yok." -ForegroundColor Green
            }
            if ($hasFailure) { exit 1 }
        } else {
            Write-Host "  [!] Serial capture olusmadi: $SerialCapture" -ForegroundColor Red
            exit 1
        }
    } else {
        Write-Host "  Simics aciliyor (VGA + Serial + Konsol)..." -ForegroundColor Cyan
        & $SimicsBat $GeneratedScriptSimics
    }
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "  Bitti." -ForegroundColor Green
