
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=D:\Intel Simics Package Manager\simics-7.70.0
RAW_SIMICS_MODEL_BUILDER=D:\Intel Simics Package Manager\simics-7.70.0
RAW_EML_PACKAGE=
RAW_DODOC_PKG=D:\Intel Simics Package Manager\simics-7.70.0
RAW_PYTHON_PKG=D:\Intel Simics Package Manager\simics-python-7.14.0\win64\bin\..\..

RAW_SIMICS_PACKAGE_LIST=C:\Users\Bahadir\Desktop\dersler_ve_projeler\echOS\Simics\echos-simics\.package-list

INCLUDE_PATHS = D:\Intel Simics Package Manager\simics-7.70.0\src\include
CXX_INCLUDE_PATHS = D:\Intel Simics Package Manager\simics-7.70.0\win64\api
DML_INCLUDE_PATHS = D:\Intel Simics Package Manager\simics-7.70.0\win64\bin\dml\api
HOST_TYPE = win64
