param(
    [string]$OutputDir = "artifacts\curated-bundles",
    [string]$DownloadDir = "artifacts\curated-downloads",
    [string]$SourceDir = "artifacts\curated-sources",
    [switch]$SkipPosting
)

$ErrorActionPreference = "Stop"

$CommercialSafeLicenses = @(
    "MIT",
    "Apache-2.0",
    "MIT OR Apache-2.0",
    "Apache-2.0 OR MIT",
    "MPL-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Zlib",
    "MIT OR Unlicense",
    "Unlicense OR MIT"
)

function Get-LatestRelease {
    param([string]$Repo)
    $json = & 'C:\Windows\System32\curl.exe' -fsSL "https://api.github.com/repos/$Repo/releases/latest"
    return $json | ConvertFrom-Json
}

function Find-Asset {
    param(
        $Release,
        [string]$Pattern
    )
    return $Release.assets | Where-Object { $_.name -match $Pattern } | Select-Object -First 1
}

function Ensure-Dir {
    param([string]$Path)
    if (-not (Test-Path $Path)) {
        New-Item -ItemType Directory -Force -Path $Path | Out-Null
    }
}

function Expand-ArchivePayload {
    param(
        [string]$ArchivePath,
        [string]$Destination
    )
    if (Test-Path $Destination) {
        Remove-Item $Destination -Recurse -Force
    }
    New-Item -ItemType Directory -Force -Path $Destination | Out-Null
    if ($ArchivePath.EndsWith(".zip")) {
        Expand-Archive -LiteralPath $ArchivePath -DestinationPath $Destination -Force
        return
    }
    if ($ArchivePath.EndsWith(".tar.gz")) {
        & tar -xzf $ArchivePath -C $Destination
        if ($LASTEXITCODE -ne 0) {
            throw "tar extraction failed for $ArchivePath"
        }
        return
    }
    throw "Unsupported archive type: $ArchivePath"
}

function New-CuratedManifest {
    param(
        [string]$AppId,
        [string]$Title,
        [string]$Entry
    )
@"
app_id = "$AppId"
name = "$Title"
version = "1.0.0"
entry = "$Entry"
sdk_version = 1
runtime = "pe"
presentation = "shell-owned"
capabilities = ["fs.read", "dialogs.open", "dialogs.save", "notifications.post", "clipboard.read", "clipboard.write"]
default_window.title = "$Title"
default_window.width = 1240
default_window.height = 820
state_contract = "warm-suspend"
restart_policy = "never"
"@
}

function Write-Utf8NoBom {
    param(
        [string]$Path,
        [string]$Content
    )
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

function Get-EchSdkBinary {
    $sdkExe = Join-Path $PSScriptRoot "..\\target\\x86_64-pc-windows-msvc\\debug\\echsdk.exe"
    $sdkExe = [System.IO.Path]::GetFullPath($sdkExe)
    if (-not (Test-Path $sdkExe)) {
        & cargo build --quiet --target x86_64-pc-windows-msvc --bin echsdk
        if ($LASTEXITCODE -ne 0) {
            throw "cargo build failed for echsdk"
        }
    }
    if (-not (Test-Path $sdkExe)) {
        throw "echsdk.exe not found at $sdkExe"
    }
    return $sdkExe
}

function Assert-LicenseAllowed {
    param(
        [string]$Slug,
        [string]$License
    )
    if ([string]::IsNullOrWhiteSpace($License)) {
        throw "Curated app $Slug is missing a verified license field."
    }
    if ($CommercialSafeLicenses -notcontains $License) {
        throw "Curated app $Slug uses disallowed or unreviewed license '$License'."
    }
}

function Write-LicenseAudit {
    param(
        [string]$Path,
        [object[]]$Apps
    )
    $lines = @(
        "# Curated App License Audit",
        "",
        "This file is generated by `scripts/package_curated_apps.ps1`.",
        "",
        "| App | License | Source | Notes |",
        "| --- | --- | --- | --- |"
    )
    foreach ($app in $Apps) {
        $lines += "| $($app.title) | $($app.license) | https://github.com/$($app.repo) | commercial-safe allowlist |"
    }
    $lines += ""
    $lines += "Warning: this audit does not change the workspace root license. If echOS remains under AGPL, commercial distribution constraints still exist regardless of curated app licenses."
    Write-Utf8NoBom -Path $Path -Content ($lines -join "`r`n")
}

function Write-CuratedSeedImage {
    param(
        [string]$OutputPath,
        [string[]]$BundlePaths
    )
    $bundleFiles = $BundlePaths | Where-Object { Test-Path $_ } | Sort-Object
    $entries = @()
    foreach ($bundle in $bundleFiles) {
        $identity = [System.IO.Path]::GetFileNameWithoutExtension($bundle)
        $data = [System.IO.File]::ReadAllBytes($bundle)
        $entries += [PSCustomObject]@{
            Identity = $identity
            IdentityBytes = [System.Text.Encoding]::UTF8.GetBytes($identity)
            Data = $data
        }
    }
    $stream = [System.IO.File]::Open($OutputPath, [System.IO.FileMode]::Create, [System.IO.FileAccess]::Write, [System.IO.FileShare]::None)
    try {
        $writer = New-Object System.IO.BinaryWriter($stream, [System.Text.Encoding]::UTF8, $false)
        $writer.Write([byte[]][System.Text.Encoding]::ASCII.GetBytes("echSID01"))
        $writer.Write([UInt16]1)
        $writer.Write([UInt16]$entries.Count)
        $writer.Write([UInt32]0)
        $payloadOffset = 16
        foreach ($entry in $entries) {
            $payloadOffset += 20 + $entry.IdentityBytes.Length
        }
        foreach ($entry in $entries) {
            $writer.Write([UInt64]$payloadOffset)
            $writer.Write([UInt64]$entry.Data.Length)
            $writer.Write([UInt16]$entry.IdentityBytes.Length)
            $writer.Write([UInt16]0)
            $writer.Write([byte[]]$entry.IdentityBytes)
            $payloadOffset += $entry.Data.Length
        }
        foreach ($entry in $entries) {
            $writer.Write([byte[]]$entry.Data)
        }
        $writer.Flush()
    }
    finally {
        $stream.Dispose()
    }
}

function Copy-ExecutablePackage {
    param(
        [string]$Slug,
        [string]$Title,
        [string]$ExecutablePath,
        [string]$BundleOut,
        [string]$SourceRoot,
        [string]$SdkExe
    )
    $packageRoot = Join-Path $SourceRoot $Slug
    if (Test-Path $packageRoot) {
        Remove-Item $packageRoot -Recurse -Force
    }
    New-Item -ItemType Directory -Force -Path $packageRoot | Out-Null
    $entryName = Split-Path $ExecutablePath -Leaf
    Copy-Item $ExecutablePath (Join-Path $packageRoot $entryName) -Force
    $manifest = New-CuratedManifest -AppId $Slug -Title $Title -Entry $entryName
    Write-Utf8NoBom -Path (Join-Path $packageRoot "echos-app.toml") -Content $manifest
    & $SdkExe sign $packageRoot developer $BundleOut
    if ($LASTEXITCODE -ne 0) {
        throw "echsdk sign failed for $Slug"
    }
}

Ensure-Dir $OutputDir
Ensure-Dir $DownloadDir
Ensure-Dir $SourceDir
$sdkExe = Get-EchSdkBinary

$apps = @(
    @{ slug = "helix"; title = "Helix"; repo = "helix-editor/helix"; asset = "x86_64-windows\.zip$"; exe = "hx.exe"; license = "MPL-2.0" },
    @{ slug = "yazi"; title = "Yazi"; repo = "sxyazi/yazi"; asset = "x86_64-pc-windows-msvc\.zip$"; exe = "yazi.exe"; license = "MIT" },
    @{ slug = "zellij"; title = "Zellij"; repo = "zellij-org/zellij"; asset = "^zellij-x86_64-pc-windows-msvc\.zip$"; exe = "zellij.exe"; license = "MIT" },
    @{ slug = "bottom"; title = "bottom"; repo = "ClementTsang/bottom"; asset = "^bottom_x86_64-pc-windows-msvc\.zip$"; exe = "btm.exe"; license = "MIT" },
    @{ slug = "gitui"; title = "GitUI"; repo = "gitui-org/gitui"; asset = "^gitui-win\.tar\.gz$"; exe = "gitui.exe"; license = "MIT" },
    @{ slug = "glow"; title = "Glow"; repo = "charmbracelet/glow"; asset = "Windows_x86_64\.zip$"; exe = "glow.exe"; license = "MIT" },
    @{ slug = "ripgrep"; title = "ripgrep"; repo = "BurntSushi/ripgrep"; asset = "x86_64-pc-windows-msvc\.zip$"; exe = "rg.exe"; license = "Unlicense OR MIT" },
    @{ slug = "fd"; title = "fd"; repo = "sharkdp/fd"; asset = "x86_64-pc-windows-msvc\.zip$"; exe = "fd.exe"; license = "Apache-2.0 OR MIT" },
    @{ slug = "bat"; title = "bat"; repo = "sharkdp/bat"; asset = "x86_64-pc-windows-msvc\.zip$"; exe = "bat.exe"; license = "Apache-2.0 OR MIT" }
)

foreach ($app in $apps) {
    Assert-LicenseAllowed -Slug $app.slug -License $app.license
    Write-Host ("Packaging curated app: {0}" -f $app.slug) -ForegroundColor Cyan
    $release = Get-LatestRelease -Repo $app.repo
    $asset = Find-Asset -Release $release -Pattern $app.asset
    if (-not $asset) {
        throw "No matching asset found for $($app.repo)"
    }
    $archivePath = Join-Path $DownloadDir $asset.name
    if (-not (Test-Path $archivePath)) {
        & 'C:\Windows\System32\curl.exe' -fL $asset.browser_download_url -o $archivePath
        if ($LASTEXITCODE -ne 0) {
            throw "Download failed for $($asset.browser_download_url)"
        }
    }
    $extractRoot = Join-Path $DownloadDir ($app.slug + "-extract")
    Expand-ArchivePayload -ArchivePath $archivePath -Destination $extractRoot
    $exe = Get-ChildItem $extractRoot -Recurse -Filter $app.exe | Select-Object -First 1
    if (-not $exe) {
        throw "Executable $($app.exe) not found for $($app.slug)"
    }
    $bundleOut = Join-Path $OutputDir ($app.slug + ".bhd")
    Copy-ExecutablePackage -Slug $app.slug -Title $app.title -ExecutablePath $exe.FullName -BundleOut $bundleOut -SourceRoot $SourceDir -SdkExe $sdkExe
}

if (-not $SkipPosting) {
    Assert-LicenseAllowed -Slug "posting" -License "Apache-2.0"
    Write-Host "Packaging curated app: posting (source build)" -ForegroundColor Cyan
    $postingRoot = Join-Path $DownloadDir "posting-root"
    if (Test-Path $postingRoot) {
        Remove-Item $postingRoot -Recurse -Force
    }
    Ensure-Dir $postingRoot
    & cargo install --root $postingRoot --target x86_64-pc-windows-msvc --git https://github.com/darrenburns/posting --locked posting
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "Posting git install failed; curated set will continue without Posting."
        Write-Host ("Curated bundles ready in {0}" -f (Resolve-Path $OutputDir)) -ForegroundColor Green
        exit 0
    }
    $postingExe = Join-Path $postingRoot "bin\\posting.exe"
    if (-not (Test-Path $postingExe)) {
        Write-Warning "Posting executable not found after install; curated set will continue without Posting."
        Write-Host ("Curated bundles ready in {0}" -f (Resolve-Path $OutputDir)) -ForegroundColor Green
        exit 0
    }
    Copy-ExecutablePackage -Slug "posting" -Title "Posting" -ExecutablePath $postingExe -BundleOut (Join-Path $OutputDir "posting.bhd") -SourceRoot $SourceDir -SdkExe $sdkExe
}

Write-CuratedSeedImage -OutputPath (Join-Path $OutputDir "curated-seed.img") -BundlePaths (Get-ChildItem $OutputDir -Filter *.bhd | ForEach-Object { $_.FullName })
Write-LicenseAudit -Path (Join-Path $OutputDir "LICENSES-curated-apps.md") -Apps ($apps + @([pscustomobject]@{ title = "Posting"; repo = "darrenburns/posting"; license = "Apache-2.0" }))
Write-Host ("Curated bundles ready in {0}" -f (Resolve-Path $OutputDir)) -ForegroundColor Green
